# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20170319_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'My Subscriber', 'verbose_name_plural': 'Whole lotta subs'},
        ),
    ]
