# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductInOrder',
            new_name='ProdInOrder',
        ),
    ]
