# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20170322_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.DeleteModel(
            name='ProductInOrder',
        ),
    ]
